// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Fk1LpCO1BX7IDSA7TGKFIRAuH4tMg1o',
    appId: '1:408021366021:web:3d1be55120065aa2ec736c',
    messagingSenderId: '408021366021',
    projectId: 'todoapp-64a62',
    authDomain: 'todoapp-64a62.firebaseapp.com',
    storageBucket: 'todoapp-64a62.appspot.com',
    measurementId: 'G-ZWSK6QXK2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPXLrn9tUv2WYdW4W2XnTrspaR5JBzGs',
    appId: '1:408021366021:android:03aedd44e7e6bdb9ec736c',
    messagingSenderId: '408021366021',
    projectId: 'todoapp-64a62',
    storageBucket: 'todoapp-64a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSc4FXvCiz-4j_dD_GGUzM447UD39Hzo',
    appId: '1:408021366021:ios:5443d09ad6e6db51ec736c',
    messagingSenderId: '408021366021',
    projectId: 'todoapp-64a62',
    storageBucket: 'todoapp-64a62.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABSc4FXvCiz-4j_dD_GGUzM447UD39Hzo',
    appId: '1:408021366021:ios:666bb082e7ba649bec736c',
    messagingSenderId: '408021366021',
    projectId: 'todoapp-64a62',
    storageBucket: 'todoapp-64a62.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
